## Write a Numpy program to compute the multiplication of two given matrixes

In [4]:
import numpy as np
data=np.array([[1,2,3],[3,4,5]])
data2=np.array([[1,2,3],[3,4,5]])
data3=data*data2
print(data3)

[[ 1  4  9]
 [ 9 16 25]]


## Write a NumPy program to compute the determinant of a given square array

In [13]:
import numpy as np
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
data1=np.linalg.det(data)
print(data1)

6.66133814775094e-16


## Write a NumPy program to compute the cross product of two given vectors

In [29]:
import numpy as np
data=np.array([1,2,3])
data2=np.array([1,2,3])
data3=data2.dot(data)
data4=np.cross(data,data2)
print(data3)
print(data4)

14
[0 0 0]


## Write a NumPy program to compute the condition number of a given matrix

In [16]:
from numpy import linalg as LA
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print("Original matrix:")
print(a)
print("The condition number of the said matrix:")
print(LA.cond(a))

Original matrix:
[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]
The condition number of the said matrix:
1.4142135623730951


## Write a NumPy program to compute the inverse of a given matrix

In [27]:
import numpy as np
data=np.array([[1,2,2],[4,4,5],[6,6,7]])
data1=np.linalg.inv(data)
dataIden=data.dot(data1)
print(data1)
print(dataIden)

[[-1.  -1.   1. ]
 [ 1.  -2.5  1.5]
 [ 0.   3.  -2. ]]
[[ 1.00000000e+00 -8.88178420e-16  4.44089210e-16]
 [ 0.00000000e+00  1.00000000e+00  1.77635684e-15]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
